name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: bash ./gradlew test --stacktrace
