name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  ci:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: bash ./gradlew test --stacktrace


  release:
    name: Release APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app/build/outputs/apk/debug/app-debug.apk
          tag: ${{ github.ref }}
          asset_name: Paranoid_${{ github.ref }}_${{ github.sha }}.apk
          prerelease: true
          release_name: Paranoid v1e-9
